backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

# media_library:
#   name: uploadcare
#   config:
#     publicKey: 447953d48939ee18e1b0

collections:
  - name: "features"
    label: "Features"
    folder: "src/pages/features"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/pages/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "testimonials",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "Hero Content Image", name: "heroimage", widget: image }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Energy Lab Title,
                    name: energyLabTitle,
                    widget: string,
                  },
                  {
                    label: Energy Lab Subtitle,
                    name: energyLabSubtitle,
                    widget: string,
                  },
                  {
                    label: Energy Lab Logo,
                    name: energyLabLogo,
                    widget: image,
                  },
                  {
                    label: Energy Lab Description,
                    name: energyLabDescription,
                    widget: text,
                  },
                ],
            }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: text },
                        { label: Description, name: desc, widget: text },
                        { label: Link, name: link, widget: text },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/start-here/index.md"
        label: "Start Here"
        name: "startHere"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "start-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - { label: "Body", name: "body", widget: markdown }
          - { label: Image One, name: imageOne, widget: image }
          - { label: Image Two, name: imageTwo, widget: image }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: text },
                  { label: Description, name: desc, widget: markdown },
                ],
            }
          - {
              label: "Call to Action",
              name: "cto",
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Body", name: "body", widget: markdown },
                ],
            }
      - file: "src/pages/small-group-coaching/index.md"
        label: "Small Group Coaching"
        name: "r2r"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "small-group-coaching",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - { label: "Body", name: "body", widget: markdown }
          - {
              label: "Button",
              name: "button",
              widget: object,
              fields:
                [
                  { label: "Text", name: "text", widget: "string" },
                  { label: "Link", name: "link", widget: "string" },
                ],
            }
      - file: "src/pages/energylab/index.md"
        label: "Energy Lab"
        name: "energylab"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "energylab",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - { label: "Body", name: "body", widget: markdown }
          - {
              label: "Button",
              name: "button",
              widget: object,
              fields:
                [
                  { label: "Text", name: "text", widget: "string" },
                  { label: "Link", name: "link", widget: "string" },
                ],
            }
      - file: "src/pages/swim-coaching/index.md"
        label: "Swim Coaching"
        name: "swimcoaching"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "energylab",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - { label: "Body", name: "body", widget: markdown }
          - {
              label: "Button",
              name: "button",
              widget: object,
              required: false,
              fields:
                [
                  {
                    label: "Text",
                    name: "text",
                    widget: "string",
                    required: false,
                  },
                  {
                    label: "Link",
                    name: "link",
                    widget: "string",
                    required: false,
                  },
                ],
            }
      - file: "src/pages/triathlon-coaching/index.md"
        label: "Triathlon Coaching"
        name: "tricoaching"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "energylab",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - { label: "Body", name: "body", widget: markdown }
          - {
              label: "Button",
              name: "button",
              widget: object,
              required: false,
              fields:
                [
                  {
                    label: "Text",
                    name: "text",
                    widget: "string",
                    required: false,
                  },
                  {
                    label: "Link",
                    name: "link",
                    widget: "string",
                    required: false,
                  },
                ],
            }
      - file: "src/pages/membership-options/index.md"
        label: "Membership Options"
        name: "membership"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "membership-options",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - { label: "Body", name: "body", widget: markdown }
          - { label: Image One, name: imageOne, widget: image }
          - { label: Image Two, name: imageTwo, widget: image }
          - {
              label: Membership Tiers,
              name: tiers,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: text },
                  { label: Price, name: price, widget: text },
                  { label: Description, name: desc, widget: markdown },
                ],
            }
          - {
              label: "Call to Action",
              name: "cto",
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Body", name: "body", widget: markdown },
                ],
            }
      - file: "src/pages/sponsors/index.md"
        label: "Sponsors"
        name: "sponsors"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "sponsors",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - {
              label: Sponsors,
              name: sponsors,
              widget: list,
              fields:
                [
                  { label: Link, name: link, widget: text },
                  { label: Logo, name: logo, widget: image },
                ],
            }
      - file: "src/pages/atc-coaches/index.md"
        label: "ATC Coaches"
        name: "atc-coaches"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "atc-coaches",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - {
              label: Coaches,
              name: coaches,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: text },
                  { label: Image, name: image, widget: image },
                  { label: About, name: about, widget: markdown },
                ],
            }
      - file: "src/pages/triathlon-coaches/index.md"
        label: "Energy Lab 1:1 Triathlon Coaches"
        name: "triathlon-coaches"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "atc-coaches",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - {
              label: Coaches,
              name: coaches,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: text },
                  { label: Image, name: image, widget: image },
                  { label: About, name: about, widget: markdown },
                ],
            }
      - file: "src/pages/swim-coaches/index.md"
        label: "Energy Lab 1:1 Swim Coaches"
        name: "swim-coaches"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "atc-coaches",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - {
              label: Coaches,
              name: coaches,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: text },
                  { label: Image, name: image, widget: image },
                  { label: About, name: about, widget: markdown },
                ],
            }
      - file: "src/pages/training-locations/index.md"
        label: "Training Locations"
        name: "training-locations"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "training-locations",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Accent Image", name: "accentimage", widget: image }
          - {
              label: Locations,
              name: locations,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Address, name: address, widget: string },
                  { label: Details, name: details, widget: text },
                ],
            }
